[package]
name = "rust-kzg-bn254"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
ark-bn254 = "0.4.0"
ark-ec = "0.4.2"
ark-ff = "0.4.1"
ark-serialize = "0.4.2"
ark-std = "0.4.0"
directories = "5.0.1"
hex-literal = "0.4.1"
rand = "0.8.5"
sha2 = "0.10.8"
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = "0.3.18"
ureq = "2.9.6"
num-bigint = "0.4"
rayon = "1.5"
num-traits = "0.2"
byteorder = "1.4"
