[package]
name = "rust-kzg-bn254"
version = "0.1.0"
edition = "2021"
authors = ["Anup Swamy Veena"]
rust-version = 1.73
description = "This library offers a set of functions for generating and interacting with bn254 KZG commitments and proofs in rust, with the motivation of supporting fraud and validity proof logic in EigenDA rollup integrations."
readme = "README.md"
repository = "https://github.com/Layr-Labs/rust-kzg-bn254"
license-file = "LICENSE"

[dependencies]
ark-bn254 = "0.4.0"
ark-ec = "0.4.2"
ark-ff = "0.4.1"
ark-serialize = "0.4.2"
ark-std = "0.4.0"
directories = "5.0.1"
hex-literal = "0.4.1"
rand = "0.8.5"
sha2 = "0.10.8"
ureq = "2.9.6"
num-bigint = "0.4"
rayon = "^1.5"
num-traits = "0.2"
byteorder = "1.4"
ark-poly = "0.4.2"
crossbeam-channel = "0.5"
num_cpus = "^1.16.0"

[dev-dependencies]
criterion = "0.5"
lazy_static = "1.4"

[[bench]]
name = "bench_g1_ifft"
harness = false

[[bench]]
name = "bench_kzg_setup"
harness = false

[[bench]]
name = "bench_kzg_commit"
harness = false

[[bench]]
name = "bench_kzg_proof"
harness = false

[[bench]]
name = "bench_kzg_verify"
harness = false

[profile.bench]
opt-level = 3
debug = true
strip = "none"
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

[profile.test]
opt-level = 3
debug = true
strip = "none"
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

